framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
        handler_id: null
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_samesite: lax
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: 'MYSESSIONID'
        # Other available options you might want:
        cookie_lifetime: 0
        cookie_httponly: true
        gc_maxlifetime: 1440

parameters:
    app.espace.default: 'snack'