# config/services.yaml
parameters:
    app.espace.default: 'snack'
    app.espace.cache_ttl: 3600

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $espaceActuel: '%app.espace.default%'

    App\Service\BorneContext:
        arguments:
            $cache: '@cache.app'

    App\Repository\EspaceRepository:
        factory: ['@doctrine', getRepository]
        arguments:
            - App\Entity\Espace

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'